language: php
sudo: required
dist: trusty
group: edge

php:
  - hhvm
  - hhvm-nightly
  - hhvm-3.24

before_script: composer install

script:
  - hh_server --check $(pwd)
  - composer run-script tests
